### ISSUE TITLE
Cannot Install Because of the wrong manifest.json link

### ISSUE THREAD

**Issue by Quorafind** [akaalias/obsidian-extract-pdf#1]
The manifest.json link to : https://github.com/akaalias/obsidian-extract-pdf/releases/download/0.0.3/manifest.json

But the real link in this reposity is https://github.com/akaalias/obsidian-extract-pdf/releases/download/0.0.03/manifest.json

I think 0.0.3 and 0.0.03 is different that made people cannot install the plugin

**Comment by akaalias** [comment]
Great catch, thank you for posting. I've updated the release number, please try again and let me know
