### ISSUE TITLE
Plugin prevents PDF preview in Obsidian

### ISSUE THREAD

**Issue by psyguy** [akaalias/obsidian-extract-pdf#2]
Hi,

I recently noticed the PDFs are not being previewed in Obsidian. By trial and error, I disabled/enabled plugins one by one, and apparently, this plugin is causing the problem.

I'm on Obsidian v0.10.7 and using plugin version 0.0.6.

**Comment by akaalias** [comment]
Hi @psyguy! Thank you for reporting and I'm sorry for the inconvenience. I updated the plugin recently to work with v0.10.8 - which was a big issue for days. Ideally, please update your Obsidian version and let me know if the problem is still appearing!

**Comment by psyguy** [comment]
Thanks, @akaalias, it works now with 0.10.8.

I am going to open another issue for some feature suggestions 😉 .
