### ISSUE TITLE
Extract math formulas from the PDF and including in the markdown note

### ISSUE THREAD

**Issue by psyguy** [akaalias/obsidian-extract-pdf#3]
Many papers have (LaTeX) math formulas and expressions, either inline or as separate equations. These are not extracted properly.

For instance, the following bit of a paper I'm reading:

![image](https://user-images.githubusercontent.com/8527082/105536010-fad2f300-5cef-11eb-881e-2f8339e049cf.png)

Is extracted as:

```
 In the multilevel literature it has been well recognized that using the model inEquation 2as the basis of a multilevel regression analysis will lead to a slope estimate that represents neither the within-cluster slope( w ), nor the between-cluster slope( b ).Ifwe refer to this estimated slope asˆ, it has been shown that it is a weighted sum of the estimated slopes at both levels, that is 

  ˆ ˆ ( b )(1) ˆ ( w )  ˆ ( w )( ˆ ( b ) ˆ ( w )) 

##### (3) 

 wherecan be thought of as a measure indicating the relative amount of variability at the between-cluster level compared to the total variability in the data across all clusters and time points (Mundlak, 1978;Neuhaus & Kalbfleisch, 1998;Raudenbush & Bryk, 2002). Hence, the weightis not the intraclass correlation, which is independent of the number of time points; instead it is a direct function of the number of time points and becomes smaller as the number of time points increases, as we will see later. The weighted sumis represented as the dashed line inFigure 2, which lies somewhere between the within-person slope( w )and the between-person slope( b ).

```

And rendered as:

![image](https://user-images.githubusercontent.com/8527082/105535955-e131ab80-5cef-11eb-83e1-5b052e965574.png)

It would be great if solved. Thanks in advance!

**Comment by akaalias** [comment]
HI @psyguy thank you so much for sharing! As I point out in the readme, the parsing is limited. I won't have the time to expand the underlying library to handle anything but text. Even that still needs some TLC. 

To keep this moving forward, do you have an example service or app that does what you're looking for already? (Maybe they've published some better parsing library we can look at.) Let me know!

**Comment by psyguy** [comment]
Hi again, @akaalias, and thanks for the reply.

I have used the awesome [pdf2htmlEX](https://github.com/coolwanglu/pdf2htmlEX) a couple of times, which converts PDF to gorgeous HTML while keeping the formating intact.
In its wiki, there is [a comparison](https://github.com/coolwanglu/pdf2htmlEX/wiki/Comparison) with other services.

I have also found [pdf2md](https://github.com/jzillmann/pdf-to-markdown) (live here pdf2md.morethan.io) that uses [pdf.js](https://github.com/mozilla/pdf.js/). It does not extract figures, but can partially extract math.

I found [this shell library](https://github.com/arpitjainds/Extract-PDF-Images) for image extraction, but haven't tried yet.
