### ISSUE TITLE
icon too clear

### ISSUE THREAD

**Issue by Mara-Li** [akaalias/obsidian-extract-pdf#6]
Hello !
This plugin is great, but I cannot see the icon with light mode : 
![image](https://user-images.githubusercontent.com/30244939/113264181-f5d38680-92d2-11eb-91f8-e15d73df53ed.png)
(VS dark mode: 
![image](https://user-images.githubusercontent.com/30244939/113264252-0be14700-92d3-11eb-992e-74dbbcd524aa.png)

**Comment by j-peeters** [comment]
I have the same problem. Might is be an idea to make the color a variable one that themes like California Coast and Minimal Theme use? I see it's now a hardcoded 'white' Thanks!

**Comment by Mara-Li** [comment]
> 
> 
> I have the same problem. Might is be an idea to make the color a variable one that themes like California Coast and Minimal Theme use? I see it's now a hardcoded 'white' Thanks!

Hello ! I success to change the image to take the currentcolor (as the other icon). Here is the files : 
[pdf-to-markdown-plugin.zip](https://github.com/akaalias/obsidian-extract-pdf/files/6397533/pdf-to-markdown-plugin.zip)

**Comment by j-peeters** [comment]
Fabulous @Mara-Li Thanks.
Hopefully the plugin developer will implement your code in the release.
Have you considered doing a Pull request in Github and doing a code change suggestion in it?

**Comment by Mara-Li** [comment]
I think i will do that in some hours yes :)

**Comment by Mara-Li** [comment]
So I do the pull request ! https://github.com/akaalias/obsidian-extract-pdf/pull/9#issue-628572846

**Comment by aeophie** [comment]
2021/11/21 This problem still exists
